<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKjxwmr0\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKjxwmr0/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerKjxwmr0.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerKjxwmr0\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerKjxwmr0\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Kjxwmr0',
    'container.build_id' => 'aadb1cb8',
    'container.build_time' => 1536591682,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerKjxwmr0');
