<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZl8imf4\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZl8imf4/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerZl8imf4.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerZl8imf4\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerZl8imf4\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Zl8imf4',
    'container.build_id' => '10887725',
    'container.build_time' => 1536944135,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerZl8imf4');
